### ISSUE TITLE
[Issue]: 2.1 models don't load default .yaml config

### ISSUE THREAD

**Issue by Razunter** [vladmandic/automatic#470]
### Issue Description

Can't switch to some 2.1 SD models, while base 2.1 and some others load fine. This doesn't happen in the original repo + Torch 2.
Removing all extensions (including the built-in ones) didn't help.

```
changing setting sd_model_checkpoint to 2.0\custom\digitalDiffusion_v10.safetensors: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\Soft\StableDiffusion-Automatic1111-fork\modules\shared.py:526 in set                                              │
│                                                                                                                      │
│   525 │   │   │   try:                                                                                               │
│ ❱ 526 │   │   │   │   self.data_labels[key].onchange()                                                               │
│   527 │   │   │   except Exception as e:                                                                             │
│                                                                                                                      │
│ D:\Soft\StableDiffusion-Automatic1111-fork\modules\call_queue.py:16 in f                                             │
│                                                                                                                      │
│    15 │   │   with queue_lock:                                                                                       │
│ ❱  16 │   │   │   res = func(*args, **kwargs)                                                                        │
│    17                                                                                                                │
│                                                                                                                      │
│                                               ... 21 frames hidden ...                                               │
│                                                                                                                      │
│ D:\Soft\StableDiffusion-Automatic1111-fork\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl      │
│                                                                                                                      │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                       │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                                              │
│   1502 │   │   # Do not call functions when jit is used                                                              │
│                                                                                                                      │
│ D:\Soft\StableDiffusion-Automatic1111-fork\venv\lib\site-packages\torch\nn\modules\linear.py:114 in forward          │
│                                                                                                                      │
│   113 │   def forward(self, input: Tensor) -> Tensor:                                                                │
│ ❱ 114 │   │   return F.linear(input, self.weight, self.bias)                                                         │
│   115                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: mat1 and mat2 must have the same dtype
```

No launch params.

Settings:
![settings 1](https://user-images.githubusercontent.com/362900/234124680-b0e13813-b682-4aca-b847-290a2bae9546.png)
![settings 2](https://user-images.githubusercontent.com/362900/234124776-f68ba25f-35e8-4f68-b1d7-e0f094bbabd8.png)

[setup.log](https://github.com/vladmandic/automatic/files/11314926/setup.log)

Not a recent issue, just was too lazy to report it.
<hr>
Unrelated:

1. On startup, the UI is displayed before the model is loaded, but there is no loading indicator, leading to confusion/errors.
2. If hires fix is enabled by default on startup, the corresponding UI section remains hidden.

### Version Platform Description

```
01:42:10-838363 INFO     Version: 82d7b45c Mon Apr 24 16:54:12 2023 -0400
01:42:11-663924 INFO     nVidia toolkit detected
01:42:20-111164 INFO     Torch 2.0.0+cu118
01:42:20-138222 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
01:42:20-140223 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10240 Arch (8, 6) Cores 68
```
Windows 11

**Comment by vladmandic** [comment]
Can you post a link to one such model?

**Comment by Razunter** [comment]
Ugh, sorry, forgot.
https://civitai.com/models/48858

**Comment by Razunter** [comment]
OK, this is caused by the lack of the `.yaml` file. But it works fine in the original repo, corresponding yaml loads automatically from defaults, I guess.

**Comment by vladmandic** [comment]
It should here as well, leave it open and I'll check when backlog dies down.

**Comment by vladmandic** [comment]
i've checked and when loading digitial-diffusion model repo automatically applies correct default configuration even without having a model yaml file present.

> Loading weights: /home/vlado/dev/automatic/models/Stable-diffusion/digital-diffusion-v10.safetensors 
> Creating model from config: /home/vlado/dev/automatic/repositories/stable-diffusion-stability-ai/configs/stable-diffusion/v2-inference-v.yaml
> LatentDiffusion: Running in v-prediction mode

you can see in console that it applied v2 config and model is a v-type model (sd15 models are so called eps-type models).

**Comment by vladmandic** [comment]
ok, thats more info to work with, i'll check.

**Comment by vladmandic** [comment]
@Razunter any updates? If issue persists, can you post new console log?

**Comment by Razunter** [comment]
Sorry, somehow missed the previous message.
Still have the problem. Probably Windows specific. No `Creating model from config`.
The problem is extremely minor, as it can be solved with symlinks or simply placing models in the default location.

```
Loading weights: d:\Soft\StableDiffusion-Automatic1111\models\Stable-diffusion\2.0\custom\digitalDiffusion_v20.safeten…
changing setting sd_model_checkpoint to 2.0\custom\digitalDiffusion_v20.safetensors: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\Soft\StableDiffusion-Automatic1111-fork\modules\shared.py:501 in set                                              │
│                                                                                                                      │
│   500 │   │   │   try:                                                                                               │
│ ❱ 501 │   │   │   │   self.data_labels[key].onchange()                                                               │
│   502 │   │   │   except Exception as e:                                                                             │
│                                                                                                                      │
│ D:\Soft\StableDiffusion-Automatic1111-fork\modules\call_queue.py:16 in f                                             │
│                                                                                                                      │
│    15 │   │   with queue_lock:                                                                                       │
│ ❱  16 │   │   │   res = func(*args, **kwargs)                                                                        │
│    17                                                                                                                │
│                                                                                                                      │
│                                               ... 23 frames hidden ...                                               │
│                                                                                                                      │
│ D:\Soft\StableDiffusion-Automatic1111-fork\extensions-builtin\a1111-sd-webui-lycoris\lycoris.py:740 in               │
│ lyco_Linear_forward                                                                                                  │
│                                                                                                                      │
│   739 │                                                                                                              │
│ ❱ 740 │   return torch.nn.Linear_forward_before_lyco(self, input)                                                    │
│   741                                                                                                                │
│                                                                                                                      │
│ d:\Soft\StableDiffusion-Automatic1111-fork\venv\lib\site-packages\torch\nn\modules\linear.py:114 in forward          │
│                                                                                                                      │
│   113 │   def forward(self, input: Tensor) -> Tensor:                                                                │
│ ❱ 114 │   │   return F.linear(input, self.weight, self.bias)                                                         │
│   115                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: mat1 and mat2 must have the same dtype
```

**Comment by vladmandic** [comment]
minor or not, i'd like to fix it.
can you post longer console log leading to error (no need for traceback once error happens). i'd want to see everything from server startup until you switch model and it fails.

**Comment by Razunter** [comment]
Not much there, and the important part looks hidden in `... 23 frames hidden ...` even with --debug.
[log.log](https://github.com/vladmandic/automatic/files/11371240/log.log)

**Comment by vladmandic** [comment]
based on your log...

first loaded model: `d:\Soft\StableDiffusion-Automatic1111\models\Stable-diffusion\2.0\mix\rmadaMergeSD21768_v70.safetensors`
which was created using custom config: `d:\Soft\StableDiffusion-Automatic1111\models\Stable-diffusion\2.0\mix\rmadaMergeSD21768_v70.yaml`

then tried to load second model: `d:\Soft\StableDiffusion-Automatic1111\models\Stable-diffusion\2.0\custom\digitalDiffusion_v20.safetensors`
which does not have its config

that model also appears to be 2.0 model as well so app did not try to recreate config, but instead use existing one.
but they don't seem to be compatible.

there are slight differences in config files and they cannot be dynamically detected.
if first model was something detectable as different (like 1.5 model), app should switch config on its own. but this was just too close.
in general, which config should be used for which model (unless model has its config) is pretty much best-guess.

i don't think this has anything to do with models being in different folders.

**Comment by Razunter** [comment]
Config should be the same for both, both are standard 2.0 models. But yeah, changing the folder to default by itself didn't fix the issue. But it works with default config, investigating.

**Comment by Razunter** [comment]
It's slightly different, but the bug happens when switching from 1.5 models too.

`rmadaMergeSD21768_v70.yaml`:
```
model:
  base_learning_rate: 1.0e-4
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    parameterization: "v"
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "image"
    cond_stage_key: "caption"
    image_size: 64
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False # we set this to false because this is an inference only config

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        use_checkpoint: True
        use_fp16: True
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          #attn_type: "vanilla-xformers"
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
            - 1
            - 2
            - 4
            - 4
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenOpenCLIPEmbedder
      params:
        freeze: True
        layer: "penultimate"
```

Loading model on start works fine, but breaks when switching. [New log](https://github.com/vladmandic/automatic/files/11374212/log2.log).
